# OBJS = ast.cmo semantic_analyzer.cmo sast.cmo linecounter.cmo parser.cmo scanner.cmo irgenerator.cmo compile.cmo spwag.cmo
OBJS = ast.cmo sast.cmo linecounter.cmo parser.cmo scanner.cmo irgenerator.cmo irtester.cmo compile.cmo spwag.cmo
# OBJS = ast.cmo sast.cmo linecounter.cmo parser.cmo scanner.cmo spwag.cmo


spwag: $(OBJS)
	ocamlc -o spwag $(OBJS)

irtester: ast.cmo sast.cmo irgenerator.cmo irtester.cmo
	ocamlc -o irtester ast.cmo sast.cmo irgenerator.cmo irtester.cmo

compiletester: sast.cmo ir.cmo compile.cmo compiletester.cmo
	ocamlc -o compiletester sast.cmo ir.cmo compile.cmo compiletester.cmo

scanner.ml: scanner.mll
	ocamllex scanner.mll

parser.ml parser.mli: parser.mly
	ocamlyacc parser.mly

%.cmo: %.ml
	ocamlc -c $<

%.cmi: %.mli
	ocamlc -c $<

.PHONY: clean
clean:
	rm -f parser.ml parser.mli scanner.ml *.cmo *.cmi spwag irtester compiletester

# Generated by ocamldep *.ml *.mli
ast.cmo :
ast.cmx :
compile.cmo : ir.cmo
compile.cmx : ir.cmx
compiletester.cmo : ir.cmo
compiletester.cmx : ir.cmx
ir.cmo : sast.cmo
ir.cmx : sast.cmx
irgenerator.cmo : sast.cmo ir.cmo
irgenerator.cmx : sast.cmx ir.cmx
irtester.cmo : sast.cmo irgenerator.cmo ast.cmo
irtester.cmx : sast.cmx irgenerator.cmx ast.cmx
linecounter.cmo :
linecounter.cmx :
parser.cmo : linecounter.cmo ast.cmo parser.cmi
parser.cmx : linecounter.cmx ast.cmx parser.cmi
sast.cmo : ast.cmo
sast.cmx : ast.cmx
semantic_analyzer.cmo :
semantic_analyzer.cmx :
spwag.cmo : parser.cmi compile.cmo ast.cmo
spwag.cmx : parser.cmx compile.cmx ast.cmx
parser.cmi : ast.cmo

